# Generated by Django 4.2.7 on 2023-11-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('rarity', models.CharField(blank=True, max_length=20, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('card_types', models.CharField(blank=True, max_length=20, null=True)),
                ('attack', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('weaknesses', models.CharField(blank=True, max_length=20, null=True)),
                ('card_number', models.CharField(blank=True, max_length=4, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('evolution_stage', models.CharField(blank=True, max_length=20, null=True)),
                ('special_abilities', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
