# Generated by Django 4.2.7 on 2023-12-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0005_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PokemonCards',
            new_name='PokemonCard',
        ),
    ]
